# Generated by Django 4.0.3 on 2022-03-08 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploadData', models.DateTimeField(auto_now_add=True, null=True)),
                ('githubLink', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
                ('liveSiteLink', models.URLField(blank=True, null=True)),
                ('contributers', models.JSONField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('recruiting', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('apealDate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Unverified'), ('2', 'in Talk'), ('3', 'Accepted'), ('4', 'Rejected')], default='Pending', max_length=50, null=True)),
                ('apealedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtrackerapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('commentDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtrackerapp.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('priority', models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low'), ('4', 'Unknown')], default='2', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Resolved'), ('4', 'Rejected')], default='1', max_length=50, null=True)),
                ('msg', models.TextField(blank=True, max_length=200, null=True)),
                ('reportDate', models.DateField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtrackerapp.project')),
                ('reportedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
