# Generated by Django 4.0.3 on 2022-03-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signedAs', models.CharField(blank=True, choices=[('1', 'Developer'), ('2', 'Tester'), ('3', 'Project Manager'), ('4', 'Admin'), ('5', 'User')], max_length=200, null=True)),
                ('technology', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
