# Generated by Django 4.0.3 on 2022-03-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0004_project_file_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
    ]
