# Generated by Django 4.0.3 on 2022-03-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0005_remove_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
