# Generated by Django 4.0.3 on 2022-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bug-screenshot'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
