# Generated by Django 4.0.3 on 2022-03-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0009_alter_bug_priority_alter_bug_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signedAs',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('User', 'User')], default='User', max_length=200, null=True),
        ),
    ]
