# Generated by Django 4.0.3 on 2022-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0010_alter_userprofile_signedas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reportDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
