# Generated by Django 4.0.3 on 2022-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0011_alter_bug_reportdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reportDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
