# Generated by Django 4.0.4 on 2022-05-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0014_featurerequest_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtrackerapp.userprofile'),
        ),
    ]
