# Generated by Django 4.0.4 on 2022-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0016_project_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
