# Generated by Django 4.0.4 on 2022-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrackerapp', '0017_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
